import fs from 'fs';
import os from 'os';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, '..');
const port = process.env.VITE_PORT || '5173';

const VIRTUAL_IP_PREFIXES = ['192.168.56.', '172.16.', '169.254.'];

function scoreAdapter(name, ip) {
  if (VIRTUAL_IP_PREFIXES.some((p) => ip.startsWith(p))) return -10;
  const n = (name || '').toLowerCase();
  if (n.includes('virtual') || n.includes('vethernet') || n.includes('vmware') || n.includes('hyper-v')) {
    return -10;
  }
  if (n.includes('wi-fi') || n.includes('wifi') || n.includes('wlan')) return 20;
  if (n.includes('ethernet') || n.includes('eth')) return 15;
  if (ip.startsWith('192.168.')) return 5;
  if (ip.startsWith('10.')) return 3;
  return 0;
}

function pickLanIp() {
  let best = null;
  for (const [name, ifaces] of Object.entries(os.networkInterfaces())) {
    for (const net of ifaces ?? []) {
      if (net.family !== 'IPv4' || net.internal) continue;
      const score = scoreAdapter(name, net.address);
      if (!best || score > best.score) {
        best = { ip: net.address, score, name };
      }
    }
  }
  return best?.ip ?? null;
}

const ip = pickLanIp();
const envPath = path.join(root, '.env.local');

if (!ip) {
  console.warn(
    '[detect-lan] No LAN IPv4 found. Connect to Wi-Fi, then restart. QR codes will not work on phones until VITE_PUBLIC_URL is set.'
  );
  process.exit(0);
}

const publicUrl = `http://${ip}:${port}`;
const lines = [
  '# Auto-generated by scripts/detect-lan.mjs — safe to regenerate on each npm run dev',
  `VITE_PUBLIC_URL=${publicUrl}`,
  '# API uses Vite proxy (/api -> Spring Boot) so phones only need port 5173',
  'VITE_API_URL=/api',
  '',
];

fs.writeFileSync(envPath, lines.join('\n'), 'utf8');
console.log(`[detect-lan] Mobile QR / public portal URL base: ${publicUrl}`);
console.log('[detect-lan] If this IP is wrong, set VITE_PUBLIC_URL manually in .env.local');
console.log(`[detect-lan] Open on phone: ${publicUrl}/verify?token=...`);
console.log(`[detect-lan] Wrote ${envPath}`);
